import { useState, useEffect } from 'react';
import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Form from '@/components/Form';
import SearchResults from '@/components/SearchResults';

export default function Home() {
  const [formData, setFormData] = useState(null);
  const [fetchResults, setFetchResults] = useState(null);

  useEffect(() => {
    if (formData === null) return;

    const fetchResults = async () => {
      const response = await fetch(
        '/api/handlerHealthProviders?' +
          (formData?.lastName ? `last_name=${formData.lastName}` : '') +
          (formData?.firstName ? `&first_name=${formData.firstName}` : '') +
          (formData?.city ? `&city=${formData.city}` : '') +
          (formData.state ? `&state=${formData.state}` : '')
      );

      if (!response.ok) {
        throw new Error('Something went wrong in index.js!');
      }

      const data = await response.json();

      setFetchResults(data);
    };

    fetchResults();
  }, [formData]);

  const formSubmissionHandler = (formSubmissionData) => {
    setFormData(formSubmissionData);
  };

  let searchResults = '';

  if (fetchResults?.result_count > 0) {
    searchResults = <SearchResults searchResults={fetchResults} />;
  }

  if (fetchResults?.result_count === 0) {
    searchResults = <div>No Results Found</div>;
  }

  return (
    <>
      <Head>
        <title>Health Care Provider Search</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Form onFormSubmission={formSubmissionHandler} />
        {searchResults}
      </main>
    </>
  );
}
